### ISSUE TITLE
Не возвращает спсок файлов

### ISSUE THREAD

**Issue by asagynbaev** [ErzhanKub/FilePrinterAPI#1]
Эндпоинт  /file-systems/files/

В качестве параметра попробовал передать D:\ - не вернул
Попробовал передать D:\\ тоже самое, получил пустой список

**Comment by erzhanKub** [comment]
Интересно, в теории прога должна работать. К сожалению у меня только c:\ стоит, без внешнего принтера.

В чем может быть причина: 

1.  При передаче D:\\, если права ограничены и некоторые системные файлы и каталоги защищены то можно получить - Access to the path 'c:\\Documents and Settings' is denied. А так как пришел пустой массив проблем не совсем в этот. 
2. Эндпоинт передает input данные в метод GetAllFilesAsync, который в свою очередь получает все файлы из каталога и всех его подкаталогов, затем фильтрует по _allowedExtensions(".doc", ".docx", . . .). Возможно в d:\ просто нет файлов с такими расширениями. 
Example: C:\Games\testFP вернул статсу код 200 и пустой массив [ ].
3. Могут быть проблемы если програ запущена в контейнере (возможно  еще в облачной среде). 

В целом, я попробую поискать инфо на счет этой проблемы и попросить у друзей флешку, для проверки работоспособности.
Мне еще не помешали бы больше инфо о проблеме, с вашей стороны, чтобы сузить круг поиска. Mb проблема еще может возникнуть в среде.

**Comment by erzhanKub** [comment]
Интересно, в теории прога должна работать. К сожалению у меня только
c:\ стоит, без внешнего принтера.

В чем может быть причина:

1. При передаче D:\, если права ограничены и некоторые системные файлы
и каталоги защищены то можно получить - Access to the path
'c:\Documents and Settings' is denied. А так как пришел пустой массив
проблем не совсем в этот.
2. Эндпоинт передает input данные в метод GetAllFilesAsync, который в
свою очередь получает все файлы из каталога и всех его подкаталогов,
затем фильтрует по _allowedExtensions(".doc", ".docx", . . .).
Возможно в d:\ просто нет файлов с такими расширениями.
Example: C:\Games\testFP вернул статсу код 200 и пустой массив [ ].
3. Могут быть проблемы если програ запущена в контейнере (возможно еще
в облачной среде).

В целом, я попробую поискать инфо на счет этой проблемы и попросить у
друзей флешку, для проверки работоспособности.
Мне еще не помешали бы больше инфо о проблеме, с вашей стороны, чтобы
сузить круг поиска. Mb проблема еще может возникнуть в среде.


ср, 22 нояб. 2023 г. в 23:17, AZIMBEK SAGYNBAEV ***@***.***>:

**Comment by erzhanKub** [comment]
Я на вашу почту отправил важную информацию

чт, 23 нояб. 2023 г. в 10:05, Эржан Кубанычбек уулу ***@***.***
